= Embedded Alien React App
:source-highlighter: rouge

This component was created in traditional way, then wrapped with Gradle project definition tool (formerly, build tool).

== Steps ...

=== 1. Create-React-App

.Zsh Examples
[source,bash]
----
cd ..   # not here!

# Default way
npx create-react-app another-react-web-client --template typescript
# or
#yarn create react-app another-react-web-client --template typescript
----

**Make sure that it works, see _<<__the_react_web,Available Scripts>>_!**
Add some more _ignore_ if necessary.

[#_2_wrap_it_with_gradle]
=== 2. Wrap it with Gradle

_It is possible to develop this component on the system that doesn't offer JSx/TSx ecosystem using only Gradle plugins._
Gradle dependencies will be automatically pulled to support JavaScript ecosystem on certain configurations.

[WARNING]
.Wrapping native JS project is a lousy approach!
====
While many conservative teams have done so, we strongly discourage this practice as **doing it right is _far_ more rewarding**!
This example shows the best, though discouraged, working copy, and it has the following properties:

* The https://github.com/srs[**_srs_**] https://github.com/srs/gradle-node-plugin[_original plugin_] is **abandoned**, which caused forks:
** NOTE: https://plugins.gradle.org/plugin/com.moowork.node[moowork] is incompatible with Gradle (6.8+).
* https://github.com/deepy[**deepy**'s] https://github.com/node-gradle/gradle-node-plugin[gradle-node-plugin] is the way to go.
* Sadly, any individual feature development work is still best done without the use of Gradle, with local node and then passed to Gradle by CI.
**
====

.Bootstrapping the Gradle Node Plugin
[source,gradle]
----
plugins {
  id("com.github.node-gradle.node") version "3.2.1"
}
----


.Then the Gradle Node Plugin Wrapper
[source,gradle]
----
node {
    version.set("18.1.0")
    npmVersion.set("8.8.0")
    yarnVersion.set("1.22.15")
    download.set(true)
}
----

=== 3 Use Cases

**https://kotlinlang.org/docs/multiplatform.html[Kotlin _Multiplatform_] should be used for https://en.wikipedia.org/wiki/Domain-driven_design[DDD] Bounded Context end-to-end development!** However, when breaking down monolith an existing https://github.com/nodejs/build[io.js module] can be moved this way https://martinfowler.com/bliki/StranglerFigApplication.html[_for strangulation_]. **It should never be left this way as its final state!**

''''

NOTE: Default instructions follow (not aware of the wrapper definition with Gradle)

== Getting Started with Create React App

This project was bootstrapped with https://github.com/facebook/create-react-app[Create React App].

=== Available Scripts

[[__the_react_web, Unadulterated React Web Client Project]]

In the project directory, you can run:

`npm start`

Runs the app in the development mode.\
Open http://localhost:3000 to view it in the browser.

The page will reload if you make edits.\
You will also see any lint errors in the console.

`npm test`

Launches the test runner in the interactive watch mode.\
See the section about https://facebook.github.io/create-react-app/docs/running-tests[running tests] for more information.

`npm run build`

Builds the app for production to the `build` folder.\
It correctly bundles React in production mode and optimizes the build for the best performance.

The build is minified and the filenames include the hashes.\
Your app is ready to be deployed!

See the section about https://facebook.github.io/create-react-app/docs/deployment[deployment] for more information.

`npm run eject`

*Note: this is a one-way operation. Once you `eject`, you can’t go back!*

If you aren’t satisfied with the build tool and configuration choices, you can `eject` at any time. This command will remove the single build dependency from your project.

Instead, it will copy all the configuration files and the transitive dependencies (webpack, Babel, ESLint, etc) right into your project so you have full control over them. All of the commands except `eject` will still work, but they will point to the copied scripts so you can tweak them. At this point you’re on your own.

You don’t have to ever use `eject`. The curated feature set is suitable for small and middle deployments, and you shouldn’t feel obligated to use this feature. However we understand that this tool wouldn’t be useful if you couldn’t customize it when you are ready for it.

=== Learn More

You can learn more in the https://facebook.github.io/create-react-app/docs/getting-started[Create React App documentation].

To learn React, check out the https://reactjs.org/[React documentation].
