---
layout: post
categories: information methodology
author:
- rdd13r
- aseix
- asei-boss
meta: 'Status Update'
tags: Hackerdom Business
---

*_Why_ am I making this component?*

Ever since ASE Inc. is launched in 2016 and formalized in 2017 there's a clear intent to publish DDD Archetypes created by our company. This proved to me much more difficult than originally expected because of two strange reasons: conservative customers, and small company bargaining position.

== Rules of Business

Everyone associated with ASE Inc. is influenced by the basic rules of American business. The job of every business is to be a profitable
brand. Each  person is a brand. Each corporation is a collection of persons. Simple as that.

=== Conservative Customers

At ASE Inc we entertain 3 (three) types of business encompassing 3 types of customers. It's inefficient and historic. Our boss, Tania (asei-boss) is working on correcting this. We have:

. Traditional American Companies in Digital Transformation (DX)
** We make Dream Teams and build business domains here
. High-tech startups in early stages of development
** We coach seed developers here
. New-tech investment and brokerage
** We make prototype components here

Category 1 are weary of Open Source Software (OSS) and prefer to share nothing. +
Category 2 are short on money, often in stealth, will take OSS but spook easily if _you_ make OSS and work for them somewhere in a timeframe. +
Category 3 only understand _Elizabeth Holmes_ type of business venture - hushed up vaporware.

*And so we find it very difficult to publish OSS components _as part our business_* even though all of our production code is made from such archetype catalogs.

=== Small Company

As a company of 3 people, collaborating with a dozen of other companies of 1-3 people *we're essentially a _pushover_*. With lack of an ability to sell independently we're not in a position to dictate behavior to our customers even when in the position of leadership with the customer.

== And then?

And so in 2020 Tania ordered us finding a way to OSS for us and our partners. This idea is part of the ongoing effort to share openly.